# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'memerewind' do
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for memerewind

  target 'memerewind-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memerewindTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'memerewind-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for memerewind-tvOS

  target 'memerewind-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
